---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: bits-test-app-us-02
  region: us-east-1
  version: "1.32"
availabilityZones:
- us-east-1a
- us-east-1b
managedNodeGroups:
- name: linux-managed-nodes
  labels:
    role: managed-nodes
  instanceType: t3a.medium
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20
nodeGroups:
- name: linux-unmanaged-nodes
  labels:
    role: unmanaged-nodes
  instanceType: t3a.medium
  spot: true
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20