apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: github-runner-scaler
  namespace: github-runners
spec:
  scaleTargetRef:
    name: github-runner
    kind: Deployment
    apiVersion: apps/v1
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: github-runner
    metadata:
      owner: spandan1460
      repo: self-hosted-runner-BITS-Assignment
      runnerType: "repo"
      runnerScope: "repo"
      personalAccessTokenFromSecret: github-pat